### ISSUE TITLE
[1.2.4] crashes on startup

### ISSUE THREAD

**Issue by hvdklauw** [Direwolf20-MC/MiningGadgets#81]
first off, thanks for releasing 1.2.4 was really waiting for the void upgrade fix, however when updating to 1.2.4 in Enigmatica 4 I got this error:

```
[18Apr2020 16:34:36.868] [modloading-worker-3/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: com/direwolf20/mininggadgets/common/network/packets/PacketExtractUpgrade
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2068/549208447@6a20eaac
		2: net.minecraftforge.eventbus.EventBus$$Lambda$2068/549208447@53ee034
java.lang.NoClassDefFoundError: com/direwolf20/mininggadgets/common/network/packets/PacketExtractUpgrade
	at com.direwolf20.mininggadgets.common.network.PacketHandler.register(PacketHandler.java:33)
	at com.direwolf20.mininggadgets.MiningGadgets.setup(MiningGadgets.java:69)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.direwolf20.mininggadgets.common.network.packets.PacketExtractUpgrade
	at java.lang.ClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:103)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 19 more

[18Apr2020 16:34:36.877] [modloading-worker-6/INFO] [quark/]: Loading Module Reacharound Placing
[18Apr2020 16:34:36.870] [modloading-worker-3/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLCommonSetupEvent dispatch for modid mininggadgets
java.lang.NoClassDefFoundError: com/direwolf20/mininggadgets/common/network/packets/PacketExtractUpgrade
	at com.direwolf20.mininggadgets.common.network.PacketHandler.register(PacketHandler.java:33) ~[?:1.2.4]
	at com.direwolf20.mininggadgets.MiningGadgets.setup(MiningGadgets.java:69) ~[?:1.2.4]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:28.2]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_191]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_191]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_191]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_191]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_191]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: com.direwolf20.mininggadgets.common.network.packets.PacketExtractUpgrade
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:103) ~[modlauncher-4.1.0.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	... 19 more
```

**Comment by hvdklauw** [comment]
[2020-04-18-1.log](https://github.com/Direwolf20-MC/MiningGadgets/files/4496814/2020-04-18-1.log)
The whole logfile, but I think the above is all that is needed.

**Comment by hvdklauw** [comment]
Ok, when I open the Jar file with my zip tool I can find the PacketExtractUpgrade.class, but it's actually in `com\direwolf20\mininggadgets\common\network\Packets\` not sure if the capital P there is the issue.

**Comment by hvdklauw** [comment]
Ok, unpacking the jar, renaming the folder to `packets` rezipping and renaming the file fixed it for me.

**Comment by MichaelHillcox** [comment]
Let me check it

**Comment by MichaelHillcox** [comment]
Fixed, build failed but said it was successful... Re-released, you can grab the new on here https://github.com/Direwolf20-MC/MiningGadgets/releases/tag/1.14.4-1.2.4 until Curse approve the download
